Report comparative info for detector scores
leondz/garak pull request #814
Opened 2024-07-31 10:23 UTC by leondz

2024-08-01 17:47 UTC, leondz commented
Yup, done!

2024-08-01 23:34 UTC, jmartin-tech approved these changes

2024-08-01 23:49 UTC, jmartin-tech requested changes
Due to #813 the resource files here need to replace `ContinueSlursReclaimedSlurs80` with `ContinueSlursReclaimedSlursMini`.

2024-08-02 04:58 UTC, leondz commented
Outstanding catch

2024-08-02 06:09 UTC, merged