Include max_prompts in prompt injections
leondz/garak pull request #843
Opened 2024-08-20 12:30 UTC by mmajewsk

Somehow, the arguments that can be defined for probes via CLI, are not making it to the probes. In this case this small changes gives back the ability to set up max_probes argument. This is kind of workaround since, the value of the arguments should be automatically loaded on that stage. Nonetheless ability to set up the number of probes is useful for testing purposes.

I have read the DCO Document and I hereby sign the DCO

2024-08-20 12:31 UTC, mmajewsk commented
recheck

2024-08-20 12:33 UTC, mmajewsk commented
recheck

2024-08-20 12:34 UTC, leondz commented
think this might be too efficient/clever for CLAAssistant - can you try the "I have read..." comment on its own?

2024-08-20 12:35 UTC, mmajewsk commented
I have read the DCO Document and I hereby sign the DCO

2024-08-20 12:36 UTC, mmajewsk commented
recheck

2024-08-20 13:12 UTC, jmartin-tech requested changes
The configurable functionality does not currently support global options for a all instances of a plugin `type`. However there is already support for application of a config for an entire module such as `probes.promptinject`.

`load_data_all_attacks` should not be accessing `_config.plugins.probes`, the value of `self.max_prompts` can be set specifically for `promptinject` class probes if passed via config.

The following would set `max_prompts` for all  `promptinject` classes in this probe package.

```
plugins:
  probes:
    promptinject:
      max_prompts: 30
```

2024-08-20 14:08 UTC, mmajewsk commented
> plugins:
>   probes:
>     promptinject:
>       max_prompts: 30

Can you point me where this kind of config is explained?

2024-08-20 16:39 UTC, jmartin-tech commented
There is definitely some work needed to provide documentation of configuration support with examples, the feature was actually added somewhat recently via #711. At this time the [comments on tests](https://github.com/leondz/garak/blob/0ab62d22f8c0525935416529af62ed38faa0fe64/tests/test_configurable.py) for `Configurable` and comments on related PRs are the very limited documentation and definitely a bit obscure to discover. More work is ongoing in this area.

The initial use cases for `Configurable` plugins targeted being able to pass local device resources as seen in #777, and #810 (an example config is in the description), however the implementation was made more general in anticipation of plugins that might have some knobs to tweak.

2024-08-22 20:06 UTC, jmartin-tech commented
Closing this in favor of better documentation for utilizing `Configurable` feature for plugins.

2024-08-22 20:06 UTC, closed without merging