generator: Groq API
leondz/garak pull request #896
Opened 2024-09-04 12:33 UTC by mmilenkovic-groq

Add support for LLMs hosted via Groq's OpenAI-compatible API.

2024-09-04 12:37 UTC, mmilenkovic-groq commented
recheck

2024-09-04 12:56 UTC, leondz commented
Thank you! Will take a look.

2024-09-04 21:00 UTC, jmartin-tech requested changes
Pretty straight forward, minor adjustments requested.

2024-09-04 21:00 UTC, jmartin-tech commented on tests/generators/test_groq.py
> +    assert isinstance(result[0], str), "GroqChat _call_model should return a list"
```suggestion
    assert isinstance(result[0], str), "GroqChat generate() should contain a str"
```

2024-09-04 21:00 UTC, jmartin-tech commented on tests/generators/test_groq.py
Currently no tests would every be run in automation. Can these test be expanded to provide a `mock` response as well a response?

See: `tests/generators/test_openai.py` and `tests/generators/conftest.py` for existing patterns that should be viable here.

2024-09-05 09:18 UTC, mmilenkovic-groq commented on tests/generators/test_groq.py
I've added GroqChat to the openai-compatible tests to avoid duplication and I've added an extra test which will run in automation. Let me know if you want to add anything else here as well

2024-09-06 13:10 UTC, jmartin-tech approved these changes

2024-09-06 13:32 UTC, merged